-- highlight rules shared by the wade-* colorschemes; each scheme passes a palette
local M = {}

function M.apply(name, C)
  vim.cmd("highlight clear")
  vim.g.colors_name = name
  vim.o.termguicolors = true
  local hl = function(g, o) vim.api.nvim_set_hl(0, g, o) end
  -- base
  hl("Normal",        { fg = C.fg, bg = C.bg })
  hl("NormalNC",      { fg = C.fg, bg = "NONE" })
  hl("NormalFloat",   { fg = C.fg, bg = "NONE" })
  hl("FloatBorder",   { fg = C.mute, bg = "NONE" })
  hl("WinSeparator",  { fg = C.mute, bg = "NONE" })
  hl("LineNr",        { fg = C.mute })
  hl("CursorLine",    { bg = C.cursorline })
  hl("CursorLineNr",  { fg = C.accent, bold = true })
  hl("Visual",        { bg = C.visual })
  hl("Search",        { fg = C.bg, bg = C.accent })
  hl("CurSearch",     { fg = C.bg, bg = C.rose, bold = true })
  hl("MatchParen",    { fg = C.accent, bold = true, underline = true })

  -- classic syntax (covers older highlighters)
  hl("Comment",       { fg = C.comment, italic = true })
  hl("String",        { fg = C.cream })
  hl("Character",     { fg = C.cream })
  hl("Number",        { fg = C.rose })
  hl("Float",         { fg = C.rose })
  hl("Boolean",       { fg = C.deep, bold = true })
  hl("Constant",      { fg = C.deep })
  hl("Identifier",    { fg = C.fg })
  hl("Function",      { fg = C.rose })
  hl("Keyword",       { fg = C.accent, bold = true })
  hl("Statement",     { fg = C.accent, bold = true })
  hl("Conditional",   { fg = C.accent, bold = true })
  hl("Repeat",        { fg = C.accent, bold = true })
  hl("Label",         { fg = C.accent })
  hl("Operator",      { fg = C.magenta })
  hl("Exception",     { fg = C.accent, bold = true })
  hl("PreProc",       { fg = C.deep })
  hl("Include",       { fg = C.accent, italic = true })
  hl("Define",        { fg = C.accent, italic = true })
  hl("Macro",         { fg = C.deep })
  hl("Type",          { fg = C.deep })
  hl("StorageClass",  { fg = C.deep, italic = true })
  hl("Structure",     { fg = C.deep })
  hl("Typedef",       { fg = C.deep })
  hl("Special",       { fg = C.accent })
  hl("Delimiter",     { fg = C.dim })
  hl("Todo",          { fg = C.bg, bg = C.accent, bold = true })

  -- treesitter (modern @-captures override the classic ones)
  hl("@variable",            { fg = C.fg })
  hl("@variable.parameter",  { fg = C.cream, italic = true })
  hl("@variable.member",     { fg = C.rose })
  hl("@variable.builtin",    { fg = C.deep, italic = true })
  hl("@property",            { fg = C.rose })
  hl("@function",            { fg = C.rose })
  hl("@function.call",       { fg = C.rose })
  hl("@function.method",     { fg = C.rose })
  hl("@function.builtin",    { fg = C.accent, italic = true })
  hl("@function.macro",      { fg = C.accent, italic = true })
  hl("@constructor",         { fg = C.deep })
  hl("@type",                { fg = C.deep })
  hl("@type.builtin",        { fg = C.deep, italic = true })
  hl("@type.definition",     { fg = C.deep, bold = true })
  hl("@keyword",             { fg = C.accent, bold = true })
  hl("@keyword.return",      { fg = C.accent, bold = true })
  hl("@keyword.function",    { fg = C.accent, bold = true })
  hl("@keyword.operator",    { fg = C.accent })
  hl("@keyword.import",      { fg = C.accent, italic = true })
  hl("@string",              { fg = C.cream })
  hl("@string.escape",       { fg = C.accent, bold = true })
  hl("@string.special",      { fg = C.accent })
  hl("@number",              { fg = C.rose })
  hl("@boolean",             { fg = C.deep, bold = true })
  hl("@constant",            { fg = C.deep })
  hl("@constant.builtin",    { fg = C.deep, bold = true })
  hl("@operator",            { fg = C.magenta })
  hl("@punctuation",         { fg = C.dim })
  hl("@punctuation.bracket", { fg = C.dim })
  hl("@punctuation.delimiter", { fg = C.dim })
  hl("@comment",             { fg = C.comment, italic = true })
  hl("@tag",                 { fg = C.accent })
  hl("@tag.attribute",       { fg = C.rose, italic = true })
  hl("@label",               { fg = C.accent })

  -- diagnostics — use palette tones
  hl("DiagnosticError",      { fg = C.error })
  hl("DiagnosticWarn",       { fg = C.accent })
  hl("DiagnosticInfo",       { fg = C.rose })
  hl("DiagnosticHint",       { fg = C.mute })
  hl("DiagnosticUnderlineError", { sp = C.error, undercurl = true })
  hl("DiagnosticUnderlineWarn",  { sp = C.accent, undercurl = true })

  -- telescope
  hl("TelescopeBorder",        { fg = C.mute, bg = "NONE" })
  hl("TelescopeNormal",        { bg = "NONE" })
  hl("TelescopePromptBorder",  { fg = C.accent, bg = "NONE" })
  hl("TelescopePromptNormal",  { bg = "NONE" })
  hl("TelescopePromptPrefix",  { fg = C.accent })
  hl("TelescopeSelection",     { fg = C.fg, bg = C.selection, bold = true })
  hl("TelescopeMatching",      { fg = C.accent, bold = true })
  hl("TelescopeTitle",         { fg = C.accent, bold = true })

  -- git signs
  hl("GitSignsAdd",            { fg = C.rose })
  hl("GitSignsChange",         { fg = C.accent })
  hl("GitSignsDelete",         { fg = C.error })
end

return M
